apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-dashboard-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/tektoncd/dashboard 
  - name: revision
    value: vX.Y.Z-invalid-tags-boouuhhh # REPLACE with your own commit
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-bucket
spec:
  type: storage
  params:
   - name: type
     value: gcs
   - name: location
     value: gs://tekton-releases/dashboard # If you're testing add /test.issue.nnn to the end
   - name: dir
     value: "y"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: dashboard-image
spec:
  type: image
  params:
   - name: url
     value: cmd/dashboard # Registry is provided via parameter, this is a hack see #569
